# -*- coding: utf-8 -*-
"""Conditional_statement_answers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxX7qjDhZoLY4dWVi0qnhrNq1pfLGH9i
"""

num = int(input("Enter the number: "))

if num > 0:
    print("Positive number")
elif num < 0:
    print("Negative number")
else:
    print("Zero")

num = int(input("Enter the number: "))

if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

age = int(input("Enter your age: "))

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

mark = int(input("Enter the mark: "))

if mark >= 35:
    print("Pass")
else:
    print("Fail")

num = int(input("Enter the number: "))

if num % 5 == 0:
    print("Divisible by 5")
else:
    print("Not divisible by 5")

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a > b:
    print("A is greater, a = ", a)
else:
    print("B is greater, b = ", b)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a > b and a > c:
    print("a is Largest, a = ", a)
elif b > c:
    print("b is Largest, b = ", b)
else:
    print("c is Largest, c = ", c)

age = int(input("Enter your age: "))

if age < 13:
    print("Child")
elif age < 20:
    print("Teenager")
elif age < 60:
    print("Adult")
else:
    print("Senior Citizen")

num = int(input("Enter the number: "))

if num % 3 == 0 and num % 5 == 0:
    print("Divisible by both 3 and 5")
else:
    print("Not divisible by both")

temp = float(input("Enter the temperature: "))

if temp < 20:
    print("Cold")
elif temp <= 30:
    print("Normal")
else:
    print("Hot")

mark = int(input("Enter the mark: "))

if mark >= 90:
    print("A")
elif mark >= 75:
    print("B")
elif mark >= 50:
    print("C")
elif mark >= 35:
    print("D")
else:
    print("Fail")

num = int(input("Enter a number: "))

if num >= 10 and num <= 99:
    print("Two-digit number")
else:
    print("Not a two-digit number")

ch = input("Enter a character: ")

if ch == "a" or ch == "e" or ch == "i" or ch == "o" or ch == "u":
    print("Vowel")
else:
    print("Consonant")

height = int(input("Enter the height"))

if height > 120:
    print("Eligible for the ride")
else:
    print("Not eligible")

num = int(input("Enter a number: "))

if num > 0 and num % 2 == 0:
    print("Positive and Even")
else:
    print("Not positive and even")

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
op = input("Enter the operator: ")

if op == "+":
    print(a + b)
elif op == "-":
    print(a - b)
elif op == "*":
    print(a * b)
elif op == "/":
    print(a / b)
else:
    print("Invalid operator")

m1 = int(input("Enter the mark 1: "))
m2 = int(input("Enter the mark 2: "))
m3 = int(input("Enter the mark 3: "))

average = (m1 + m2 + m3) / 3

print("Average:", average)

if m1 >= 35 and m2 >= 35 and m3 >= 35:
    print("Pass")
else:
    print("Fail")

year = int(input("Enter the year: "))

if year % 4 == 0:
    print("Leap year")
else:
    print("Not a leap year")

a = int(input("Enter the 1st side : "))
b = int(input("Enter the 2nd side : "))
c = int(input("Enter the 3rd side : "))

if a == b and b == c:
    print("Equilateral")
elif a == b or b == c or a == c:
    print("Isosceles")
else:
    print("Scalene")

num = int(input("Enter a number: "))

if num % 2 == 0 and num % 3 == 0:
    print("Divisible by both 2 and 3")
elif num % 2 == 0:
    print("Divisible by 2")
elif num % 3 == 0:
    print("Divisible by 3")
else:
    print("Divisible by neither")

age = int(input("Enter your age: "))

if age < 5:
    print("Free")
elif age <= 12:
    print("Ticket price: ₹50")
elif age <= 59:
    print("Ticket price: ₹100")
else:
    print("Ticket price: ₹70")

username = input("Enter username: ")
password = input("Enter password: ")

if username != "madhu":
    print("Invalid Username")
elif password != "1234":
    print("Incorrect Password")
else:
    print("Login Successful")

units = int(input("Enter the electricity units: "))

if units <= 100:
    bill = units * 2
elif units <= 200:
    bill = units * 3
elif units <= 300:
    bill = units * 5
else:
    bill = units * 7

print("Electricity Bill: ₹", bill)

mark = int(input("Enter the mark: "))

if mark >= 35:
    print("Pass")

    if mark >= 90:
        print("Grade: A")
    elif mark >= 75:
        print("Grade: B")
    elif mark >= 50:
        print("Grade: C")
    else:
        print("Grade: D")

else:
    print("Fail")

amount = float(input("Enter the amount: "))

if amount < 1000:
    print("No discount")
    print("Final amount:", amount)

elif amount < 5000:
    print("10% discount")
    print("Final amount:", amount - amount * 10 / 100)

elif amount < 10000:
    print("20% discount")
    print("Final amount:", amount - amount * 20 / 100)

else:
    print("30% discount")
    print("Final amount:", amount - amount * 30 / 100)

salary = float(input("Enter the salary: "))

if salary < 250000:
    tax = 0
elif salary <= 500000:
    tax = salary * 5 / 100
elif salary <= 1000000:
    tax = salary * 20 / 100
else:
    tax = salary * 30 / 100

print("Tax: ₹", tax)

speed = int(input("Enter the speed: "))

if speed < 40:
    print("Slow")
elif speed <= 60:
    print("Normal")
elif speed <= 80:
    print("Fast")
else:
    print("Over Speed")

day = int(input("Enter the number"))

if day == 1:
    print("Monday")
elif day == 2:
    print("Tuesday")
elif day == 3:
    print("Wednesday")
elif day == 4:
    print("Thursday")
elif day == 5:
    print("Friday")
elif day == 6:
    print("Saturday")
elif day == 7:
    print("Sunday")
else:
    print("Invalid number")

month = int(input("Enter the month number: "))

if month == 2:
    print("28 or 29 days")
elif month == 4 or month == 6 or month == 9 or month == 11:
    print("30 days")
elif month >= 1 and month <= 12:
    print("31 days")
else:
    print("Invalid month")

age = int(input("Enter the age: "))
tickets = int(input("Enter the number of tickets: "))

if age < 5:
    price = 0
elif age <= 12:
    price = 50
elif age < 60:
    price = 100
else:
    price = 70

total = price * tickets

if tickets > 5:
    total = total - (total * 10 / 100)

print("Final Bill: ₹", total)