# -*- coding: utf-8 -*-
"""Practice_questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qTk8k4UOXSZ9_GIxGVTyHVrr_u4NRAR

Data structure

List
"""

colors = ["Red", "Blue", "Green"]

colors.append("White")
print(colors)

colors.extend(["Blue", "Black"])
print(colors)

colors.insert(0,"Pink")
print (colors)

colors.remove("Green")
print (colors)

colors.pop(0)
print (colors)

colors.pop()
print (colors)

numbers = [1,2,5,3,4]

numbers.reverse()
print(numbers)

numbers.sort()
print (numbers)

numbers.sort(reverse=True)
print (numbers)

print (numbers [0:3])

"""Tuple"""

student = ("Madhu", 23, "ECE")

print(student)
print(student[0])

numbers = (10, 20, 50, 30, 70, 70, 45)
letters = ('g','h','b','c','d','a', 's')

print("length of the numbers",len(numbers))
print("length of the letters",len(letters))

both = numbers+letters

print("Concatenated tuple",both)

print("Ascending order",sorted(letters))

print("Descending order",sorted(letters,reverse=True))

print(numbers.count(70))

print (letters.index('s'))

print(numbers[1])

print(letters[0:4])

print(letters[-1])

"""Dictionary"""

colors = {"Red", "Blue", "Green", "Blue"}

print(colors)

student = {
    "name": "Madhu",
    "age": 23,
    "department": "ECE"
}

print(student)

student["location"] = "Palani"
print(student)

student["department"] = "Data Analytics"
print(student)

student.pop("location")
print(student)

"""Conditional Statement

If-else statement
"""

num = 15

if num >= 18:
    print("greater")
else:
    print("lesser")

num = int(input("Enter a number"))

if num >= 0:
    print("Positive number")
else:
    print("Negative number")

num = int(input("Enter a number"))

if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

age = int(input("Enter a number"))

if age >= 18:
    print("eligible to vote")
else:
    print("not eligible to vote")

mark = int(input("Enter a number"))

if mark >= 35:
    print("Pass")
else:
    print("Fail")

a = 10
b = 20

if a > b:
    print("A is greater")
else:
    print("B is greater")

temperature = int(input("Enter a number"))

if temperature > 30:
    print("Hot")
else:
    print("Normal")

age = int(input("Enter a number"))

if age >= 18:
    print("Adult")
else:
    print("Not an Adult")

num = int(input("Enter a number"))

if num == 0:
    print("Zero")
else:
    print("Not Zero")

password = int(input("Enter a number"))

if password == "0000":
    print("Correct Password")
else:
    print("Wrong Password")

salary = int(input("Enter a number"))

if salary >= 30000:
    print("Salary is high")
else:
    print("Salary is low")

"""Elif statement"""

age = int(input("Enter the age: "))

if age < 12:
    print("Child")
elif age < 20:
    print("Teenager")
elif age < 60:
    print("Adult")
else:
    print("Senior Citizen")

marks = int(input("Enter the marks: "))

if marks >= 90:
    print("A")
elif marks >= 80:
    print("B")
elif marks >= 70:
    print("C")
elif marks >= 60:
    print("D")
else:
    print("F")

num = int(input("Enter the number: "))

if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

day = int(input("Enter the number"))

if day == 1:
    print("Monday")
elif day == 2:
    print("Tuesday")
elif day == 3:
    print("Wednesday")
elif day == 4:
    print("Thursday")
elif day == 5:
    print("Friday")
elif day == 6:
    print("Saturday")
elif day == 7:
    print("Sunday")
else:
    print("Invalid number")

units = int(input("Enter the number of units: "))

if units <= 100:
    total = units * 2
elif units <= 200:
    total = units * 3
else:
    total = units * 5

print("Total Electricity Bill =", total)

weight = float(input("Enter weight: "))
height = float(input("Enter height: "))

bmi = weight / (height * height)

if bmi < 18.5:
    print("Underweight")
elif bmi < 25:
    print("Normal")
elif bmi < 30:
    print("Overweight")
else:
    print("Obese")

a = 40
b = 20
c = 10

if a > b and a > c:
    print("a is largest")
elif b > a and b > c:
    print("b is largest")
else:
    print("c is largest")

amount = int(input("Enter the amount: "))

if amount < 1000:
    discount = 0
elif amount < 5000:
    discount = 5
elif amount < 10000:
    discount = 10
else:
    discount = 20

print("Discount =", discount, "%")

a = int(input("Enter the 1st side : "))
b = int(input("Enter the 2nd side : "))
c = int(input("Enter the 3rd side : "))

if a == b and b == c:
    print("Equilateral Triangle")
elif a == b or b == c or a == c:
    print("Isosceles Triangle")
else:
    print("Scalene Triangle")

choice = int(input("Enter the choice: "))

if choice == 1:
    print("Check Balance")
elif choice == 2:
    print("Deposit")
elif choice == 3:
    print("Withdraw")
elif choice == 4:
    print("Exit")
else:
    print("Invalid choice")