# -*- coding: utf-8 -*-
"""Practice_python_loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QruIGtk0TmCG0SwJEqU0fVpLtp14Uqwt
"""

A = [1, 2,3,4,5,6,7,8,9,10]
for i in A:
    print(i)

A = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for i in A:
  if i % 2 == 0:
    print(i)

A = [1, 2,3,4,5,6,7,8,9,10]
for i in A:
    print(5, "×", i, "=", 5 * i)

word = "Python"

for i in word:
    print(i)

A = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for i in A:
    if i == 10:
        break
    print(i)

A = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for i in A:
    if i == 10:
       continue
    print(i)

numbers = [10, 20, 30, 40, 50]

for i in numbers:
    if i == 30:
       pass
    print(i)

A = [1,2,3,4,5,6,7,8,9,10]
for i in A:
    if i % 2 == 0:
       continue
    print(i)

numbers = [5, 8, 12, 15, 20, 25]

for i in numbers:
    if i > 15:
       break
    print(i)

names = ["Arun", "Bala", "Cathy", "Divya", "Esha"]

for i in names:
    if i == "Cathy":
        continue
    if i == "Divya":
        pass
    print(i)

i = 0

while i <= 10:
    print(i)
    i = i + 2