# -*- coding: utf-8 -*-
"""Python-loops-task05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh7UVnjI2h4jXxgoWlcW2wEmrWjBW7bp

For loop
"""

A = [1,2,3,4,5,6,7,8,9,10]
for i in A:
  print(i)

for i in range(10, 0, -1):
    print(i)

for i in range(1, 51):
    if i % 2 == 0:
        print(i)

for i in range(1, 51):
    if i % 2 != 0:
        print(i)

A = [1,2,3,4,5,6,7,8,9,10]
n = int(input("Enter the number: "))

for i in A:
    print(n, "x", i, "=", n * i)

sum = 0

for i in range(1, 101):
    sum = sum + i

print(sum)

sum = 0

for i in range(1, 51):
    if i % 2 == 0:
        sum = sum + i

print(sum)

sum = 0

for i in range(1, 51):
    if i % 2 != 0:
        sum = sum + i

print(sum)

A = [1,2,3,4,5,6,7,8,9,10]
for i in A:
   print(i * i)

A = [1,2,3,4,5,6,7,8,9,10]
for i in A:
   print(i * i * i)

n = int(input("Enter the number: "))

fact = 1

for i in range(1, n + 1):
    fact = fact * i

print(fact)

n = int(input("Enter the number: "))

count = 0

for i in str(n):
    count = count + 1

print(count)

n = int(input("Enter the number: "))

sum = 0

for i in str(n):
    sum = sum + int(i)

print(sum)

n = int(input("Enter a number: "))

for i in range(1, n + 1):
    if n % i == 0:
        print(i)

n = int(input("Enter the number: "))

count = 0

for i in range(1, n + 1):
    if n % i == 0:
        count = count + 1

if count == 2:
    print("Prime number")
else:
    print("Not a Prime number")

for n in range(2, 101):
    count = 0

    for i in range(1, n + 1):
        if n % i == 0:
            count = count + 1

    if count == 2:
        print(n)

numbers = [10,20,30,40,50,60]

largest = numbers[0]

for i in numbers:
    if i > largest:
        largest = i

print(largest)

numbers = [67, 17, 8, 40, 35]

smallest = numbers[0]

for i in numbers:
    if i < smallest:
        smallest = i

print(smallest)

A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even = 0
odd = 0

for i in A:
    if i % 2 == 0:
        even = even + 1
    else:
        odd = odd + 1

print("Even:", even)
print("Odd:", odd)

A = [0,0,1,2,-3,4,5,6,-7,8,9,10]
positive = 0
negative = 0
zero = 0

for i in A:
    if i > 0:
        positive = positive + 1
    elif i < 0:
        negative = negative + 1
    else:
        zero = zero + 1

print("Positive:", positive)
print("Negative:", negative)
print("Zero:", zero)

"""While loop"""

i = 1

while i <= 10:
    print(i)
    i = i + 1

i = 10

while i >= 1:
    print(i)
    i = i - 1

i = 1

while i <= 50:
    if i % 2 == 0:
        print(i)
    i = i + 1

i = 1

while i <= 50:
    if i % 2 != 0:
        print(i)
    i = i + 1

n = int(input("Enter the input number: "))

i = 1
sum = 0

while i <= n:
    sum = sum + i
    i = i + 1

print(sum)

n = int(input("Enter the number: "))

i = 1
fact = 1

while i <= n:
    fact = fact * i
    i = i + 1

print(fact)

n = int(input("Enter the number: "))

reverse = 0

while n > 0:
    digit = n % 10
    reverse = reverse * 10 + digit
    n = n // 10

print(reverse)

n = int(input("Enter the number: "))

sum = 0

while n > 0:
    digit = n % 10
    sum = sum + digit
    n = n // 10

print(sum)

n = int(input("Enter the number: "))

count = 0

while n > 0:
    count = count + 1
    n = n // 10

print(count)

n = int(input("Enter the number: "))

inputnum = n
reverse = 0

while n > 0:
    digit = n % 10
    reverse = reverse * 10 + digit
    n = n // 10

if inputnum == reverse:
    print("Palindrome")
else:
    print("Not Palindrome")

"""Nested loop/Patterns"""

for i in range(1, 6):
    for j in range(i):
        print("*", end="")
    print()

for i in range(5, 0, -1):
    for j in range(i):
        print("*", end="")
    print()

for i in range(1, 6):
    for j in range(1, i + 1):
        print(j, end="")
    print()

for i in range(1, 6):
    for j in range(i):
        print(i, end="")
    print()

for i in range(5):
    for j in range(5):
        print("*", end="")
    print()

for i in range(1, 11):
    print("Table of", i)

    for j in range(1, 11):
        print(i, "x", j, "=", i * j)

    print()

for i in range(5):
    for j in range(1, 6):
        print(j, end=" ")
    print()

for i in range(1, 6):
    for j in range(1, i + 1):
        print(j, end="")
    print()

for i in range(1, 6):
    for j in range(1, 6):
        print(i, j)

for i in range(5):
    for j in range(5):
        print("*", end=" ")
    print()