# -*- coding: utf-8 -*-
"""Python_task03_set, dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15R0tcvzz9ZkrLjAZT72D80n1MyZ_23pi

Set
"""

list1 = [1, 2, 2, 3, 4, 4, 5]

numbers = set(list1)

print(numbers)

a = {"Madhu", "Divya", "Priya"}
b = {"Divya", "Madhu", "Ravi"}

print(a & b)

a = {"Madhu", "Divya", "Priya"}
b = {"Divya", "Madhu", "Ravi"}

print(a - b)

a = {"Madhu", "Divya", "Priya"}
b = {"Divya", "Madhu", "Ravi","Ishaan"}

print(a | b)

a = {10, 5}
b = {10, 5, 30, 4}

print(a <= b)

a = {1, 2, 3}
b = {10, 20, 30}

print(a.isdisjoint(b))

numbers = set(range(1, 21))

for i in range(2, 21, 2):
    numbers.remove(i)

print(numbers)

a = {10, 20, 30, 40}
b = {30, 40, 50, 60}

print("Union:", a | b)
print("Intersection:", a & b)
print("Difference:", a - b)

hr = {"Madhu", "Divya", "Priya"}
analyst = {"Divya", "Madhu", "Ravi"}

print(hr & analyst)

products = {101, 102, 103, 104}

id = int(input("Enter the product ID: "))

if id in products:
    print("Product was purchased")
else:
    print("Product was not purchased")

"""Dictionary"""

students = {
    "Madhu": 82,
    "Preethi": 95,
    "Divya": 76
}

highest = max(students, key=students.get)

print("Highest Mark:", highest)
print("Mark:", students[highest])

employees = {
    "Madhu": 35000,
    "Ravi": 28000,
    "Priya": 45000
}

for name, salary in employees.items():
    if salary > 30000:
        print(name, salary)

text = input("Enter the string: ")

count = {}

for char in text:
    if char in count:
        count[char] = count[char] + 1
    else:
        count[char] = 1

print(count)

text = input("Enter the text: ")

words = text.split()
count = {}

for word in words:
    if word in count:
        count[word] = count[word] + 1
    else:
        count[word] = 1

print(count)

products = {
    "Pen": 10,
    "Eraser": 20,
    "Notebook": 50
}

product = input("Enter product: ")

if product in products:
    print("Price:", products[product])
else:
    print("Product not found")

numbers = {}

for i in range(1, 11):
    numbers[i] = i * i

print(numbers)

student = {
    "Name": 'Madhu',
    "Age": 23
}

course = {
    "Course name": 'Data analytics',
    "Fee": 4000
}

student.update(course)

print(student)

students = {
    "Madhu": 87,
    "Ravi": 40,
    "Divya": 72,
    "Kiran": 25
}

passed_students = {}
failed_students = {}

for name, mark in students.items():
    if mark >= 40:
        passed_students[name] = mark
    else:
        failed_students[name] = mark

print("Pass:", passed_students)
print("Fail:", failed_students)

phonebook = {
    "Madhu": "9876543210",
    "Ravi": "1234567890"
}

name = input("Enter name to add: ")
number = input("Enter phone number: ")
phonebook[name] = number

name = input("Enter name to search: ")

if name in phonebook:
    print("Number:", phonebook[name])
else:
    print("Contact not found")

name = input("Enter name to update: ")
number = input("Enter new number: ")

if name in phonebook:
    phonebook[name] = number
    print("Updated successfully")

name = input("Enter name to delete: ")

if name in phonebook:
    del phonebook[name]
    print("Deleted successfully")

print("Phonebook:", phonebook)

cart = {
    "Apple": 5,
    "Milk": 3,
    "Bread": 2,
    "Chips":5
}

total = 0

for product, quantity in cart.items():
    total = total + quantity

print("Products in the Cart:", cart)
print("Total Quantity:", total)