# -*- coding: utf-8 -*-
"""PythonPractice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xlwt1-i2ZT2nBVCdfAchNeJwlWyKsbkE
"""

name = "Madhumitha"
print(name)

name = "Madhumitha"
age = 23
city = "palani"
print(name)
print(age)
print(city)

age = 23
print("I am", age, "years old.")

a = 10
b = 20

print(a)
print(b)

a = 10
b = 20

a, b = b, a

print(a)
print(b)

college = "Mepco Schlenk Engineering College"
print(college)

first_name = "Madhumitha"
last_name = "Madhuramannan"

print(first_name, last_name)