# -*- coding: utf-8 -*-
"""PythonTask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWslUPD76xI0P3xO6o94Ylo5APj9TWdV
"""

name = "Madhumitha"
print(name)

age = 23
print(age)

a = 5
b = 10
sum = a + b
print(sum)

a = 20
b = 10
difference = a - b
print(difference)

a = 5
b = 2
product = a * b
print(product)

a = 10
b = 2
division = a / b
print(division)

length = 10
breadth = 2
area = length * breadth
print("Area:", area)

length = 10
width = 5
perimeter = 2 * (length + width)
print("Perimeter =", perimeter)

radius = 5
area = 3.14 * radius * radius

print("Area =", area)

celsius = 30
fahrenheit = (celsius * 9/5) + 32

print("Fahrenheit =", fahrenheit)

english = 80
tamil = 97
maths = 90
science = 85
social = 87
total = english + tamil + maths + science + social
print("Total marks =", total)

a = 10
b = 20
c = 30
average = (a + b + c) / 3
print("Average =", average)

meters = 5
centimeters = meters * 100
print("Centimeters =", centimeters)

kilometers = 5
meters = kilometers * 1000
print("Meters =", meters)

principal = 10000
rate = 5
time = 2
simple_interest = (principal * rate * time) / 100
print("Simple Interest =", simple_interest)

a = 10
b = 20
a, b = b, a
print("a =", a)
print("b =", b)

name = input("Enter your name: ")
print("Hello,", name)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Sum =", a + b)

age = int(input("Enter your age: "))
print("Age after 5 years =", age + 5)

length = int(input("Enter length: "))
breadth = int(input("Enter breadth: "))
area = length * breadth
print("Area =", area)

a = 10
print(type(a))

a = 10
b = float(a)
print(b)
print(type(b))

a = 10.5
b = int(a)
print(b)
print(type(b))

a = "123"
b = int(a)
print(b)
print(type(b))

a = 123
b = str(a)
print(b)
print(type(b))

a = 10
b = 10.5
c = "Hello"
d = True
print(type(a))
print(type(b))
print(type(c))
print(type(d))

number = int(input("Enter a number: "))
square = number ** 2
print("Square =", square)

number = int(input("Enter a number: "))
cube = number ** 3
print("Cube =", cube)

price1 = 100
price2 = 200
price3 = 150
total = price1 + price2 + price3
print("Total price =", total)

name = input("Enter student name: ")
mark1 = int(input("Enter mark 1: "))
mark2 = int(input("Enter mark 2: "))
mark3 = int(input("Enter mark 3: "))
total = mark1 + mark2 + mark3
average = total / 3
print("Name =", name)
print("Total marks =", total)
print("Average marks =", average)