# -*- coding: utf-8 -*-
"""python_task03(list, tuple) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcZnIpg_UDzkBReQxwvT0lbFJdbOUeX5

List
"""

marks = [87, 85, 65, 92, 82, 75, 97, 81, 79, 90]
highest_mark = max(marks)

print("Highest mark is", highest_mark)

salary = [20000, 30000, 45000, 25000, 50000, 35000]

lowest_salary = min(salary)
highest_salary = max(salary)

print("Lowest salary is", lowest_salary)
print("Highest salary is", highest_salary)

numbers = [1, 2, 3, 4, 5]

total = sum(numbers)
average = total / len(numbers)

print("Sum of numbers", total)
print("Average of numbers", average)

numbers = [10, 15, 2, 25, 3, 35, 40]

even = []
odd = []

for n in numbers:
    if n % 2 == 0:
       even.append(n)
    else:
       odd.append(n)

print("Even numbers:", even)
print("Odd numbers:", odd)

numbers = [1, 2, 1, 3, 2, 4]

i = 0

while i < len(numbers):
    if numbers.count(numbers[i]) > 1:
        numbers.remove(numbers[i])
    else:
        i = i + 1

print(numbers)

numbers = [5, 10, 20, 50, 60]

largest = max(numbers)

numbers.remove(largest)

second = max(numbers)

print("Second largest:", second)

numbers = [10, 20, 30, 40, 50]

list1 = []

for n in numbers:
   list1.insert(0, n)

print("Reversed list:", list1)

list1 = [10, 20, 30, 40]
list2 = [30, 40, 50, 60]

common = []

for n in list1:
   if n in list2:
     common.append(n)

print(common)

cart = []

product = input("Enter product to add: ")
cart.append(product)

print("Cart:", cart)

product = input("Enter product to remove: ")
cart.remove(product)

print("Cart:", cart)

fruits = ["apple", "banana", "apple", "orange", "apple", "banana"]

item = input("Enter item: ")

count = fruits.count(item)

print("Number of occurrences of the item is:", count)



"""Tuple"""

students = ("Madhu", "Sureh", "Divya", "Preethi", "Ishaan")

for name in students:
    print(name)

numbers = (5, 10, 15, 20, 30)

print("Maximum number", max(numbers))
print("Minimum number", min(numbers))
print("Sum of numbers", sum(numbers))

numbers = (10, 20, 10, 30, 10, 20)

value = int(input("Enter value: "))

count = numbers.count(value)

print("Occurrence of a number", count)

numbers = (10, 20, 30, 40, 50)

numbers.index(40)

numbers = (1, 2, 3)
print("Tuple", numbers)

list1 = list(numbers)

list1.append(4)
list1.append(5)

numbers = tuple(list1)

print("Tuple1", numbers)

student = ("Madhu", 23, 87)

name,age,mark = student

print("Name:",name)
print("Age:",age)
print("Mark:",mark)

marks = (65, 85, 90, 87, 88, 70, 95)

count = 0

for mark in marks:
  if mark > 80:
     count = count + 1

print("Count of students scored above 80 is", count)

tuple1 = (10, 20, 30)
tuple2 = (40, 50, 60)

tuple3 = tuple1 + tuple2

print("Concatenated tuple:", tuple3)

colors = ("red", "black", "orange", "blue")

item = input("Enter the color ")

if item in colors:
    print("colour exists")
else:
    print("colour does not exist")

numbers = (10, 15, 20, 25, 30, 35, 40)

even = []

for num in numbers:
    if num % 2 == 0:
        even.append(num)
print("Even numbers:", even)
even_num = tuple(even)
print(even_num)