# -*- coding: utf-8 -*-
"""Python_Task02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0RPVY4_gUuXVAyA8S-0lEheyQrFJN38

Conditional Statement
"""

year = int(input("Enter the year: "))

if year % 400 == 0:
    print("leap year")
elif year % 100 == 0:
    print("Not a leap year")
elif year % 4 == 0:
    print("leap year")
else:
    print("Not a leap year")

age = int(input("Enter your age: "))

if age >= 60:
    print("senior citizen")
else:
    print("Not a senior citizen")

age1 = int(input("Enter age of 1st Person: "))
age2 = int(input("Enter age of 2nd Person: "))
age3 = int(input("Enter age of 3rd Person: "))

if age1 >= age2 and age1 >= age3:
    print("Person 1 is oldest")
elif age2 >= age1 and age2 >= age3:
    print("Person 2 is oldest")
else:
    print("Person 3 is oldest")

experience = int(input("Enter experience in years: "))

if experience >= 5:
    bonus = 15000
elif experience >= 3:
    bonus = 8000
elif experience >= 1:
    bonus = 6000
else:
    bonus = 1000

print("Your Diwali bonus is ₹", bonus)

books = ["B1", "B2", "B3", "B4", "B5"]
want = input("Do you want to take a book?")

if want == "yes":
    card = input("Do you have a library card? ")

    if card == "yes":
        print("Available books:", books)

        book = input("Enter the book you want: ")

        if book in books:
            books.remove(book)
            print("Book issued successfully")
            print("Remaining books:", books)
        else:
            print("Book is not available")

    else:
        print("You need a library card")

else:
    print("You don't want to take a book")

"""Loops"""

n = int(input("Enter a number: "))

fact = 1

for i in range(1, n + 1):
    fact = fact * i

print("Factorial =", fact)

n = int(input("Enter a number: "))

temp = n
sum = 0

while temp > 0:
    d = temp % 10
    sum = sum + d ** 3
    temp = temp / 10

if sum == n:
    print("Armstrong number")
else:
    print("Not an Armstrong number")

for i in range(1, 6):
    print("*" * i)

n = int(input("Enter a number: "))

sum = 0

while n > 0:
    digit = n % 10
    sum = sum + digit
    n = n / 10

print("Sum of digits =", sum)

sum = 0

for i in range(10):
    n = int(input("Enter a number: "))
    sum = sum + n

average = sum / 10

print("Average =", average)

for i in range(1, 11):
    print("Table of", i)

    for j in range(1, 11):
        print(i, "x", j, "=", i * j)

    print()

"""Functions"""

def unique_list(numbers):
    new_list = []

    for n in numbers:
        if n not in new_list:
            new_list.append(n)

    return new_list


numbers = [1, 2, 3, 3, 3, 3, 4, 5]

print(unique_list(numbers))

def count_vowels(string):
  count = 0
  for l in string:
     if l in "aeiou":
        count = count + 1
  return count

text = input("Enter a string: ")
print("Number of vowels:", count_vowels(text))

def is_prime(n):
  count = 0
  for i in range(1, n + 1):
      if n % i == 0:
         count = count + 1
  if count == 2:
      return True
  else:
      return False

num = int(input("Enter a number: "))

print(is_prime(num))

def calculator(a, b, operator):

  if operator == "+":
     return a + b
  elif operator == "-":
     return a - b
  elif operator == "*":
     return a * b
  elif operator == "/":
     return a / b
  else:
     return "Invalid operator"

n1 = int(input("Enter first number: "))
n2 = int(input("Enter second number: "))
operator = input("Enter operator (+, -, *, /): ")

print("Result:", calculator(n1, n2, operator))