# -*- coding: utf-8 -*-
"""String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uqw3GQFx_6KAvMy0Izou4YyN2lLcMpM8
"""

text = "Python Programming"
print(text[0:6])

text = "Data Analytics"
print(text[5:14])

text = "Python"
print(text[::-1])

text = "Programming"
print(text[::2])

text = "Data Science"
print(text[2:8])

"""Shallow copy creates a new outer object, but nested objects are shared between the original and copied object that is the outer list is copied, but the inner/nested lists are shared
List 1 exist,New list (list 2) is created using shallow copy, when list 2 is changed, modification occurs in both lists.
Since in shallow copy, the outer list is copied, but the inner/nested lists are shared
"""

list1 = [[1, 2], [3, 4]]

list2 = list1.copy()

print(list1)
print(list2)

list2[1][0] = 10

print(list1)
print(list2)